linter:
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    lines_longer_than_80_chars: false
    package_api_docs: false
    prefer_expression_function_bodies: true
    public_member_api_docs: false
