name: samy_app
description: Swap app for my youngster's place

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_svg: 2.0.6
  flutter_map: ^1.1.1
  http: ^0.13.4
  json_theme: ^5.0.2+6
  logger: ^1.1.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  msix: ^2.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/appainter_theme.json
    - assets/logo.svg
    - assets/background.jpg

msix_config:
  display_name: BLoC+MVU Kickstarter App
  publisher_display_name: com.gmuehlenberg
  identity_name: com.gmuehlenberg
  msix_version: 1.0.0.0
  capabilities: "internetClient"
